<?php

// Prefixes for fields and field instances

/** Prefix used on all tapascollection field base names. */
define ('TAPAS_FIELD_PREFIX', 'field_tapas_');
/** Prefix used by all Collection field instances. */
define ('TAPAS_C_INSTANCE_PRE', 'fi_tapas_c_');
/** Prefix used by all project field instances. */
define ('TAPAS_P_INSTANCE_PRE', 'fi_tapas_p_');

// The content types.

/** Machine name of the Collection content type. */
define ('TAPAS_COLLECTION', 'tapascollection_collection');

/** Machine name of the Project content type. */
define ('TAPAS_PROJECT', 'tapascollection_project');


// Other constants

/** Field name for collection-to-project OG audience link*/
define ('TAPAS_C_TO_P', 'og_tapas_c_to_p');
