<?php
/**
 * @file
 * tapasupload.module TAPAS TEI upload and transformation
 * 
 * defines tapas_record conent type, performs
 * TEI upload and validation, calls TFC transform.
 */

/** implements hook_form()
 * 
 * This has to be present even if it's just a pass-through,
 * otherwise the content type won't appear in the 
 * admin/structure/types list (I have no idea what the
 * connection is, or why)
 **/
function tapasupload_record_form($node, $form_state) {
  return node_content_form($node, $form_state);
}


/**
 * implements hook_node_info()
 *
 * Defines the TAPAS record content type
 *
 * I considered making this an entity rather than a node, since node brings
 * along extra baggage that we don't need. However, Drupal's access-control
 * system is node-based; therefore, it would be far more difficult to enforce
 * access restrictions on a custom entity than on a custom node type.
 **/

function tapasupload_node_info()
{
  return array(
    'tapas_record' => array(
      'name' => t('TAPAS Record'),
      'base' => 'tapasupload_record',
      'description' => t('Holds a TEI record along with it\'s associated metadata and TFC'),
      'has_title' => TRUE,
      'title_label' => t('Record Title'),
      'help' => '',
    ),
  );
	$content_type = node_type_set_defaults($node_example);
}

/**
 * Implements hook_node_type_insert()
 **/

function tapasupload_node_type_insert($info)
{
	if ($info->type == 'tapas_record')
	{
		// Create field instances
		field_info_cache_clear();
		field_create_instance(array(
			'field_name' => 'tapas_tei_file',
			'entity_type' => 'node',
			'bundle' => 'tapas_record',
			'label' => 'TEI File',
	));
	}

}

/**
 * Implements hook_validate()
 **/

function tapasupload_record_validate($node, $form, &$form_state)
{
	if (! isset($node->field_tapas_tei_file) && ($node->field_tapas_tei_file != '')) {
		form_set_error('field_tapas_tei_field', t("Did you forget to upload a file?"));
		return;
	}
}

/**
 * Implements hook_menu()
 **/

function tapasupload_menu()
{
  $items['admin/structure/tapas_record'] = array(
    'title' => 'TAPAS Record',
    'description' => 'Control forum hierarchy settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('forum_overview'),
    'access arguments' => array('administer forums'),
    'file' => 'forum.admin.inc',
  );


}

