<?php

/**
 * @file
 *
 * Imports migrated taxonomy terms into the new tapas site.
 */

/**
 * Implements hook_enable().
 */

function importtaxonomies_enable() {
	$vid_list = importtaxonomies_get_vids();

	_importtaxonomies_populate_simple(
		$vid_list['tapas_institution'],
		'tapas_institution',
		'taxo_institution.csv');

	//TODO: import the custom instutution fields as well.
	
	_importtaxonomies_populate_simple(
		$vid_list['forum'],
		'forum',
		'taxo_forum.csv');

	_importtaxonomies_populate_simple(
		$vid_list['project_slugs'],
		'project_slugs',
		'taxo_project_slugs.csv');

	_importtaxonomes_populate_simple(
		$vid_list['collection_slugs'],
		'collection_slugs',
		'taxo_collection_slugs.csv');
}


/**
 * Get an array of vids indexed by vocab machine name.
 */

function importtaxonomies_get_vids() {
	$vocab_list = drupal_taxonomy_vocabulary_get_names();
	$vid_list = array();

	foreach($vocab_list as $vocab) {
		$vid_list[$vocab->machine_name] = $vocab->vid;
	}

	return $vid_list;
}

/**
 * Populates a flat, name-only vocabulary.
 */

function _importtaxonomies_populate_simple($vid, $vocab_name, $file_name) {

	$filepath = drupal_get_path('module', 'importtaxonomies') . '/terms/' . $file_name;
	$term_list = file($filepath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
	foreach ($term_list as $term) {
		_importtaxonomies_save_term($vid, $vocab_name, $term);
	}
}

/**
 * Saves a taxonomy term only if it doesn't already exist.
 */
function _importtaxonomies_save_term($vid, $vocab_name, $term_name) {

	$term_array = drupal_taxonomy_get_term_by_name($term_name, $vocab_name);

	if (empty($term_array)) {
		$term = new stdObject;
		$term->vid = $vid;
		$term->name = $term_name;
		return taxonomy_term_save($term);
	}

	return FALSE;

}
